// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package wine_randomforest.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class PostProcessor extends CustomJavaAction<java.lang.String>
{
	/** @deprecated use Parameter.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Parameter;
	private final wine_randomforest.proxies.ML_Output_Entity_ML_model_mapping_Wine_RF Parameter;

	public PostProcessor(
		IContext context,
		IMendixObject _parameter
	)
	{
		super(context);
		this.__Parameter = _parameter;
		this.Parameter = _parameter == null ? null : wine_randomforest.proxies.ML_Output_Entity_ML_model_mapping_Wine_RF.initialize(getContext(), _parameter);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (Parameter.getOutput_label() == 0) {
			return "Class_0";
		} else if (Parameter.getOutput_label() == 1) {
			return "Class_1";
		} else
			return "Class_2";
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PostProcessor";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
